### ISSUE TITLE
allow to trigger initial generation immediately

### ISSUE THREAD

**Issue by leoschweizer** [pitrho/rancher-gen#1]
First of all, let me say thanks for this great project, I'm trying to build an auto-configuring Traefik setup with it.

Suppose there are already some containers running and my container with rancher-gen is not the first to start. However, rancher-gen is supposed to generate the configuration file for my reverse proxy in order to route traffic to containers based on the host names of the requests.

It looks like rancher-gen currently does not trigger immediately when it is invoked, but only when Rancher reports some changes. So I would now have to wait for some change in Rancher before any configuration gets generated, which is not really acceptable. I think I need some capability to trigger an initial generation run.

What do you think?

**Comment by alejom99** [comment]
If you specify the --stack and --service options, rancher-gen will automatically trigger the first time it runs, and every time there's a change in that service. Did you specify those two options?

**Comment by leoschweizer** [comment]
@alejom99 no, I did not, because I'm interested in _all_ stacks and services of an environment. So passing these options seems counterproductive 😉

**Comment by alejom99** [comment]
That was not the intended functionality, but I just released a new version (v0.2.0) where all container instances in the environment will be passed to the template if no filter is specified. Hopefully, this will address you issue.

**Comment by leoschweizer** [comment]
👍 awesome! Looks like this solves #2 as well.
