### ISSUE TITLE
reported data only includes changed containers

### ISSUE THREAD

**Issue by leoschweizer** [pitrho/rancher-gen#2]
This is somewhat related to #1 .

Let's say I have a lot of containers for which I need to generate configuration files. It looks like rancher-gen only has knowledge of those containers which actually did change, not all containers in the system. So my template which looks something like

```
{% for container in containers %}
  id {{container['id']}}, name {{container['name']}}, state {{container['state']}}
{% endfor %}
```

only contains one line for the container which actually changed, instead of all containers (which is what I would have expected). That also means that whenever a container changes, the (single) config file is overridden, and any information about previous containers is lost.

Is this how rancher-gen is supposed to work, or am I missing something?

**Comment by alejom99** [comment]
If you specify --stack and --service options, rancher-gen will give you the information for all containers in that service.

**Comment by leoschweizer** [comment]
This is now possible in 0.2.0. Thanks a lot!
