### ISSUE TITLE
How to build this project？

### ISSUE THREAD

**Issue by zzhao0528** [pitrho/rancher-gen#3]
Hi，i don't know how to build this project.Because i will modify some code in my company env.

**Comment by alejom99** [comment]
Rancher-gen is a Python program, so you have to make sure you have Python and Pip installed in your environment. Some linux distributions already come with python 2.7 pre-installed, so all you have to do is install Pip. For example, to install Pip in ubuntu you run:

```
sudo apt-get update && apt-get install python-pip
```

 Once you have both Python and Pip installed, then you install rancher-gen by doing:

```
pip install rancher-gen
```

After that, you can use rancher-gen as described here: https://github.com/pitrho/rancher-gen#how-to-use-rancher-gen

**Comment by zzhao0528** [comment]
@alejom99 Thanks a lot. I use python setup.py clean install to build the project.

**Comment by zzhao0528** [comment]
@alejom99 Thanks a lot. I use python setup.py clean install to build the project.
